### ISSUE TITLE
If two or more annotation pin will have same coordinate then it never gets separate out

### ISSUE THREAD

**Issue by ShahVivek** [infinum/FBAnnotationClustering#11]
If two or more annotation pin will have same coordinate then it never gets separate out
I think it should separate out at last most zoom level and shows two pins as like shows in without clustering.

**Comment by filipbec** [comment]
I don't think that's a problem because you can decide not to use clustering based on the value of `scale` in the method `- (void)mapView:(MKMapView *)mapView regionDidChangeAnimated:(BOOL)animated`

**Comment by ShahVivek** [comment]
So what should be the scale value for not to use cluster.
How can I get that value ?

**Comment by pbtura** [comment]
If the two pins are really at the same coordinates, I don't think turning off the clustering is going to help. MapKit is still going to draw one pin on top of the other. If you really want a nice UI for dealing with locations that stay clustered at max zoom, why not take advantage of the annotation callout? 

In your 'didSelectAnnotationView' method you can check for the zoom level and the annotation class. If the annotation is a cluster, you can get the 'nested' annotations and loop through them to build the callout text. If you wanted to get really fancy, you could even replace the callout with a custom view that displays your information in a scrollable list.

**Comment by filipbec** [comment]
I agree with @pbtura. The proposed solution should solve the problem.
