### ISSUE TITLE
Filter Function for Clustered Annotations

### ISSUE THREAD

**Issue by pbtura** [infinum/FBAnnotationClustering#12]
Currently there is no simple way to apply a filter to the underlying annotations once the clustering manager is initialized. Have you considered adding a variant of the 'clusteredAnnotationsWithinMapRect' that takes a function or a predicate as a parameter?

**Comment by filipbec** [comment]
Resolved by #13 

Thank you for your contribution.

**Comment by pbtura** [comment]
Glad I could help. Thank you for this awesome library.
