### ISSUE TITLE
Ignoring certain annotations when clustering

### ISSUE THREAD

**Issue by mmandell70** [infinum/FBAnnotationClustering#14]
First, thank you for a great library! It is extremely fast compared to several others that I have tried.

I have two types of annotations on the map: 1) thousands of annotations that I want to be clustered and 2) a few annotations that shouldn't be clustered.  I'm (obviously) only adding the annotations that I want clustered to the clustering manager.

After I pan/zoom the map and call ClusteredAnnotationsWithinMapRect and DisplayAnnotations to refresh the clustering, my non-clustered annotations are removed.  I reviewed the DisplayAnnotations method and realized that all annotations on the map are being removed (except userLocation), and then the annotations returned from ClusteredAnnotationsWithinMapRect are being added to the map.

I fixed this by adding my non-clustered annotations to the clustered annotations array:

```swift
// Get the clustered annotations on the visible map
var annotations = clusteringManager.clusteredAnnotationsWithinMapRect(...)

// Add any annotations that aren't part of the clustering
var toKeep = [MKAnnotation]()
for annotation in mapView.annotations {
    if annotation is ... {
        toKeep.append(...)
    }
}
// Merge arrays
annotations = annotations + toKeep

clusteringManager.displayAnnotations(annotations, onMapView: mapView)
```

Is this the best way to fix my issue?

**Comment by filipbec** [comment]
Yes, I think that's the best solution.
