### ISSUE TITLE
Changed annotation view after regionDidChangeAnimated

### ISSUE THREAD

**Issue by Pades9** [infinum/FBAnnotationClustering#17]
I have a MKAnnotations on my MKMapView. I am using FBAnnotationCluster. When is normal MKAnnotationView(not clustering), I show image(preview) to pin. But after zoom in or zoom out(regionDidChangeAnimated), these previews are changed. I dont know why, but overcomes them completely random. Can you help me?

Code 
http://pastebin.com/n8NU9A6u

![9q0rr](https://cloud.githubusercontent.com/assets/6772851/8637103/bede8c54-2881-11e5-9e52-0731e0c2aab2.jpg)

**Comment by lastMove** [comment]
It seems like a problem of reusing annotationViews (dequeueReusableAnnotationViewWithIdentifier) 
You have to ensure that all setup needed is redo when getting a dequeued view

**Comment by Dundo7** [comment]
Hi, FBAnnotationClustering is no longer maintained.
