### ISSUE TITLE
mapView didAddAnnotationViews being falsely called.

### ISSUE THREAD

**Issue by Kiirojin** [infinum/FBAnnotationClustering#18]
The aforementioned function is being called with non-leaf annotation clusters upon panning of the map. I'm trying to call an animation on newly added annotation views like in thoughtbot's application and the animation is being called on all non-leaf annotation clusters whenever the user pans, which is not desired.
```
//straight from thoughtbot
- (void)mapView:(MKMapView *)mapView didAddAnnotationViews:(NSArray *)views
{
    //views contains clusters that it shouldn't when the user pans the map.
    for (UIView *view in views) {
        [self addBounceAnnimationToView:view];
    }
}

- (void)addBounceAnnimationToView:(UIView *)view
{
    CAKeyframeAnimation *bounceAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.scale"];
    
    bounceAnimation.values = @[@(0.05), @(1.1), @(0.9), @(1)];
    
    bounceAnimation.duration = 0.6;
    NSMutableArray *timingFunctions = [[NSMutableArray alloc] initWithCapacity:bounceAnimation.values.count];
    for (NSUInteger i = 0; i < bounceAnimation.values.count; i++) {
        [timingFunctions addObject:[CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseInEaseOut]];
    }
    [bounceAnimation setTimingFunctions:timingFunctions.copy];
    bounceAnimation.removedOnCompletion = NO;
    
    [view.layer addAnimation:bounceAnimation forKey:@"bounce"];
}
```
I can only assume that clusters are always being updated or recalculated whenever the view changes, thereby hitting didAddAnnotationViews more than it's supposed to.

**Comment by pixeldock** [comment]
I am experiencing the same problem and had a quick look into it. As you assumed, the clusters are always removed and added again after the map view changes.

This happens in `FBClusteringManager`'s method `displayAnnotations:onMapView:`

Have you found a solution for this?

**Comment by pixeldock** [comment]
I found the reason for this behavior and opened a PR: https://github.com/infinum/FBAnnotationClustering/pull/19

**Comment by filipbec** [comment]
This has already been discussed: 
https://github.com/infinum/FBAnnotationClustering/issues/2#issuecomment-56293567
https://github.com/infinum/FBAnnotationClustering/pull/19#issuecomment-143047249
