### ISSUE TITLE
How to prevent cluster from converting into single annotations on zooming in?

### ISSUE THREAD

**Issue by sakshiGoel26** [infinum/FBAnnotationClustering#21]
When map is zoomed in then cluster is dispersed into single annotations, how can I disable this property of separating annotations in cluster on zooming in? I tried to set its scale =  0.0 in regionDidChangeDelegate, but then it crashed giving reason "floating point value can not be converted to Int because it is either infinite or NaN"

**Comment by filipbec** [comment]
Hi @sakshiGoel26. Replace `scale` argument with a constant value (for example 0.00001) in the line:

    [self.clusteringManager clusteredAnnotationsWithinMapRect:mapView.visibleMapRect withZoomScale:scale];

You can experiment with that value to achieve desired behaviour.
