### ISSUE TITLE
NSInvalidArgumentException.  -[__NSSetM removeObject:]: object cannot be nil

### ISSUE THREAD

**Issue by Usipov** [infinum/FBAnnotationClustering#22]
Hello there))
Thanx for the amazing tool you've created!

FBClusteringManager.m line 168
-[FBClusteringManager displayAnnotations:onMapView:]

```
NSMutableSet *before = [NSMutableSet setWithArray:mapView.annotations];
[before removeObject:[mapView userLocation]];
```

The app crashes if [mapView userLocation] returns nil

Thanx in advance!

**Comment by filipbec** [comment]
I didn't notice that before SDK 9, so it's probably a new bug.

Bugfix is here: https://github.com/infinum/FBAnnotationClustering/commit/92bf48b071fbc6a041bed7b865e23ab5eb6008d3

**Comment by Usipov** [comment]
@filipbec Thanx)
