### ISSUE TITLE
Slecting Annotation View? ::question::

### ISSUE THREAD

**Issue by MMasterson** [infinum/FBAnnotationClustering#23]
How is the select of the annotation fired? I'm trying to snap to a region and display the annotation.

**Comment by filipbec** [comment]
Hi @MMasterson,

you can do something like this:

```objective-c
- (void)mapView:(MKMapView *)mapView didSelectAnnotationView:(MKAnnotationView *)view
{
    if ([view.annotation isKindOfClass:[FBAnnotationCluster class]]) {
        FBAnnotationCluster *cluster = (FBAnnotationCluster *)view.annotation;
        
        int i = 0;
        MKMapPoint points[cluster.annotations.count];
        
        for (id<MKAnnotation> annotation in cluster.annotations){
            points[i++] = MKMapPointForCoordinate(annotation.coordinate);
        }
        
        MKPolygon *polygon = [MKPolygon polygonWithPoints:points count:i];
        MKMapRect newMapRect = [polygon boundingMapRect];
        
        [mapView setVisibleMapRect:newMapRect edgePadding:UIEdgeInsetsMake(50, 50, 50, 50) animated:YES];
    }
}
```

**Comment by Quentin-Malgaud** [comment]
hi @filipbec , thank you very much for all your work. 
I encountered the same problem as @MMasterson but I am working in swift. I am trying to translate the code above but with no great success. I don't really understand what's going on with the MKPolygon. Could you give me some hints? I could then upload the translated version here ;)

Thank you

**Comment by MMasterson** [comment]
@Quentin-Malgaud does this help?

func mapView(mapView: MKMapView, didSelectAnnotationView view: MKAnnotationView) {
    if (view.annotation is FBAnnotationCluster) {
        var cluster: FBAnnotationCluster = view.annotation as! FBAnnotationCluster
        var i: Int = 0
        var points: MKMapPoint
        for annotation: MKAnnotation in cluster.annotations {
            points[i++] = MKMapPointForCoordinate(annotation.coordinate)
        }
        var polygon: MKPolygon = MKPolygon.polygonWithPoints(points, count: i)
        var newMapRect: MKMapRect = polygon.boundingMapRect()
        mapView.setVisibleMapRect(newMapRect, edgePadding: UIEdgeInsetsMake(50, 50, 50, 50), animated: true)
    }
}

*Points is the list of the annotations you wanna show

**Comment by Quentin-Malgaud** [comment]
Hi @MMasterson, thank you very much for this one. Helped me a lot ;)
Still had to change a word here and there, if you want to edit your post: 


       func mapView(mapView: MKMapView, didSelectAnnotationView view: MKAnnotationView) {
        if view.annotation is FBAnnotationCluster {
            let cluster: FBAnnotationCluster = view.annotation as! FBAnnotationCluster
            var i: Int = 0
            var points: [MKMapPoint] = []
            
            for annotation: MKAnnotation in cluster.annotations {
                points.append(MKMapPointForCoordinate(annotation.coordinate))
                i++
            }
            
            let polygon: MKPolygon = MKPolygon(points: &points, count: i)
            let newMapRect: MKMapRect = polygon.boundingMapRect
            mapView.setVisibleMapRect(newMapRect, edgePadding: UIEdgeInsetsMake(50, 50, 50, 50), animated: true)
        }
    }


Thank you again
