### ISSUE TITLE
Disable clustering for a certain zoom level

### ISSUE THREAD

**Issue by albertoaloisi** [infinum/FBAnnotationClustering#28]
Hello, I have a map that can contain a lot pins that are very close to each other, this could create the situation that the cluster will never divide itself into single pins . Is there a way to disable the clustering, if the zoom level is greater than a certain value, and accordingly reactivate it in case returned minor than a certain value ??
Thanks in advance

**Comment by filipbec** [comment]
Right now your method `mapView:regionDidChangeAnimated:` probably looks something like this:

    [[NSOperationQueue new] addOperationWithBlock:^{
        double scale = self.mapView.bounds.size.width / self.mapView.visibleMapRect.size.width;
        NSArray *annotations = [self.clusteringManager clusteredAnnotationsWithinMapRect:mapView.visibleMapRect withZoomScale:scale];
        
        [self.clusteringManager displayAnnotations:annotations onMapView:mapView];
    }];
    
There you can check `scale` value and depending on it you can decide to use clusteringManager or not. For example:

    [[NSOperationQueue new] addOperationWithBlock:^{
        double scale = self.mapView.bounds.size.width / self.mapView.visibleMapRect.size.width;
        NSArray *annotations = nil;
        if (scale < 0.00001) {
            annotations = [self.clusteringManager clusteredAnnotationsWithinMapRect:mapView.visibleMapRect withZoomScale:scale];
        } else {
            annotations = self.allAnnotations;
        }
        [self.clusteringManager displayAnnotations:annotations onMapView:mapView];
    }];
