### ISSUE TITLE
Anyway to display image thumbs

### ISSUE THREAD

**Issue by gateway** [infinum/FBAnnotationClustering#31]
Once you have zoomed in from the cluster any way to display the photos or thumbs of those as annotations easily ?

**Comment by filipbec** [comment]
Hi @gateway,

you can get all annotations in a cluster. Every cluster has property `annotations` of type `NSArray`.

**Comment by tahoecoop** [comment]
Hello! I'm working with @gateway on this project. Just to clarify, I can get the photos as the annotations from the cluster's `annotations` property? From there I can build a popover or view or something to display these? Or is there anything built into FBAnnotationClustering to be able to display these photos inside the cluster? Any ideas? Thanks for your assistance and this great framework!

**Comment by filipbec** [comment]
You have to make your own popover or view to display photos. There is built-in component.

**Comment by tahoecoop** [comment]
Ok great, thanks a lot for everything!!
