### ISSUE TITLE
Cocoapods: the dependency 'FBAnnotationClustering' is not used in any concrete target

### ISSUE THREAD

**Issue by ersentekin** [infinum/FBAnnotationClustering#33]
In example project, i tried to run `pod install` and came up with this error:

`[!] The dependency `FBAnnotationClustering (from `../FBAnnotationClustering.podspec`)` is not used in any concrete target.`

I think adding target to dependency is a must for newer version of cocoapods. What do you think guys?

**Comment by filipbec** [comment]
Merged. Thank you!
