### ISSUE TITLE
Overlapping cluster

### ISSUE THREAD

**Issue by anilappvolution** [infinum/FBAnnotationClustering#35]
Two clusters are overlapping. How to increase area of cluster? Any Solution about it?

**Comment by anilappvolution** [comment]
Please give me answer otherwise please remove this repository?

**Comment by filipbec** [comment]
You can use `FBClusteringManagerDelegate`.

**Comment by anilappvolution** [comment]
Thank you very much for your reply. It fixed my issues. This is great library which I’ve used in my project. Thank you. @filipbec

**Comment by anilappvolution** [comment]
@filipbec  Could you please help me on another stuff? How to select particular annotation from cluster?
