### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by anilappvolution** [infinum/FBAnnotationClustering#36]
In the following delegate method,
- (CGFloat)cellSizeFactorForCoordinator:(FBClusteringManager *)coordinator
  I'm return cell size 1.0, But the clusters are overlapping. I need remove cluster overlapping with cell size 1.0. It is possible? Please help me on this. Sorry for my poor english.

Thank You.

**Comment by Dundo7** [comment]
Hi, FBAnnotationClustering is no longer maintained.
