### ISSUE TITLE
No hack to remove annotations?

### ISSUE THREAD

**Issue by JoeyBodnar** [infinum/FBAnnotationClustering#39]
I see in the todo, it is planned to make a method to remove the annotation from the clustering manager. Until then, is there any hack we can use to do this? I looked through previous issues but didn't see anything. I tried self.mapView.removeAnnotations and that did not work either.

**Comment by dariopellegrini** [comment]
Maybe it should be closed because of updates, but for me clusterManager.removeAnnotations([annotation]) worked

**Comment by tarangpatel** [comment]
Remove annotation is not working for me. When i call [clusterManager removeAnnotations:annoatations] no change happens on map. I also tried to call [self.clusteringManager displayAnnotations:annotations onMapView:mapView]; after removing but it is not reflected on the map. Annotations keep on adding.

**Comment by Dundo7** [comment]
Hi, FBAnnotationClustering is no longer maintained.
