### ISSUE TITLE
Is there any way to cluster only some kind of annotations?

### ISSUE THREAD

**Issue by dariopellegrini** [infinum/FBAnnotationClustering#40]
I'm searching for a way to cluster only a list of annotations, and keep unclustered the others.
I've achieved this using:
`if let annotations = self.clusteringManager.clusteredAnnotations(within: mapView.visibleMapRect, withZoomScale: scale*2) {
                let allAnnotations: [Any] = self.notClusteringAnnotations + annotations
                self.clusteringManager.displayAnnotations(allAnnotations, on: mapView)
            }`

Is there a better way?

**Comment by Dundo7** [comment]
Hi, FBAnnotationClustering is no longer maintained.
