### ISSUE TITLE
Min zoom level on a specific annotation without it being clustered

### ISSUE THREAD

**Issue by arsonik** [infinum/FBAnnotationClustering#41]
Let's say I have an action outside the map view that need to focus an annotation on the  map.
But if the zoom level is too low then I won't see the annotation but the cluster containing the annotation.
So wouldn't it be nice to have a method like 
``
zoomScaleForUnclustered(annotation: MKAnnotation) -> Double?
``
That give you the zoom scale you need to apply to your map visible rect to display that specific annotation without it being clustered.

Cheers

**Comment by Dundo7** [comment]
Hi, FBAnnotationClustering is no longer maintained.
