### ISSUE TITLE
Have 5 annotations at same location, but on zoom they are not separated

### ISSUE THREAD

**Issue by kalyanpkumar** [infinum/FBAnnotationClustering#43]
I have 5  users in the same location and the cluster shows title as 5. Latitude and longitude are same for those users. So, as i zoom in, the cluster shows the 5 number only. The cluster is not being separated into single annotations. Everytime i zoom, the mapview delegate is called, but the cluster is not showing the separate pins at any zoom level... Can i have a solution for this..

Thanks.

**Comment by filipbec** [comment]
Hi @kalyanpkumar,

please check out this answer: https://github.com/infinum/FBAnnotationClustering/issues/28#issuecomment-196745837
