### ISSUE TITLE
Is there a way to achieve cluster onclick?

### ISSUE THREAD

**Issue by 3lywa** [infinum/FBAnnotationClustering#46]
I'm looking to implement an onclick event when a cluster is clicked in which the map will zoom in and display the sub clusters/pins. How would I go about implementing this?

**Comment by filipbec** [comment]
Hi @3lywa,

each cluster contains an array of [annotations](https://github.com/infinum/FBAnnotationClustering/blob/master/FBAnnotationClustering/FBAnnotationCluster.h#L28). Using this array you can calculate bounding box for all the annotations in the selected cluster. Then you can use [`setRegion(_:animated:)`](https://developer.apple.com/documentation/mapkit/mkmapview/1452768-setregion) method to adjust visible region.
