### ISSUE TITLE
I don't understand very well cellSizeFactorForCoordinator

### ISSUE THREAD

**Issue by Ricardo1980** [infinum/FBAnnotationClustering#5]
Hello!

I see that the delegate cellSizeFactorForCoordinator docs say:
"Cell size factor will scale size of default cell size. With value smaller than 1.0 cell size will be smaller than default and you will see more clusters on the map. With factor larger than 1.0 cell size will be bigger than default and you will see less clusters on the map."

Can anyone explain me that? What is a cell?
Thanks a lot for your time.

**Comment by Dundo7** [comment]
Hi, FBAnnotationClustering is no longer maintained.
