### ISSUE TITLE
Is there any way to deactivate the clustering?

### ISSUE THREAD

**Issue by Ricardo1980** [infinum/FBAnnotationClustering#6]
Hello!
I have a web service to retrieve all the points in the current map section. After that I call the clustering library.
Under a specific condition, I don't want to use the clustering.
Is there any way to deactivate the clustering?
Maybe a specific value in the cellSizeFactorForCoordinator delegate. Don't know.
Thanks.

**Comment by fvisticot** [comment]
Hello, Same question how to disable clusturing. In my case I would like to disable clustering starting from a zoom level ?

**Comment by filipbec** [comment]
Please take a look at #28
