### ISSUE TITLE
FBAnnotationCluster annotations not recycled

### ISSUE THREAD

**Issue by dbautist** [infinum/FBAnnotationClustering#7]
Awesome library, thanks for extending Theodore Calmes' quad-tree to be abstract and object-oriented. Lifesaver! In the interest of making it even better I think I found an issue.

I believe there is an issue in the FBClusteringManager function

`- (void)displayAnnotations:(NSArray *)annotations onMapView:(MKMapView *)mapView`

The NSSet *toKeep is always empty if you put a breakpoint at line `NSMutableSet *toAdd = [NSMutableSet setWithSet:after];`

The reason it's always empty is because every time you pan the map and call the `- (NSArray *)clusteredAnnotationsWithinMapRect:(MKMapRect)rect withZoomScale:(double)zoomScale` method, the entire array returned is all new FBAnnotationCluster objects, so when this array is passed into `displayAnnotations`, none of the FBAnnotationCluster objects in the before set will be equivalent to any of the FBAnnotationCluster objects in the after set - so intersecting the 2 sets will always yield an empty set. I hacked a solution together for my purposes by comparing on lat/long instead of by object reference but it's of course not the cleanest possible solution.

**Comment by filipbec** [comment]
This has already been discussed: #2
