### ISSUE TITLE
Swift version?

### ISSUE THREAD

**Issue by funky-monkey** [infinum/FBAnnotationClustering#9]
Hello, 

I was wondering if and when there are any plans for a Swift version of your library? (Without the need of bridging)

Best, 
Sidney

**Comment by filipbec** [comment]
I really don't have a lot of free time lately so this is not a priority for me right now. Maybe someday...

**Comment by chenr2** [comment]
Hello,

I tried to use FBAnnotationClustering in my Swift project but I ran into some performance issues after integrating it.

I ended up translating the whole thing to Swift, and it seems to be working (for the most part).  Can I post the Swift sample project on my employer's github?  This could save you the time it takes to rewrite from scratch, and I can watch your fork for bug-fixes.  

Thanks,
Rob

**Comment by funky-monkey** [comment]
@chenr2 YES PLEASE! That would be very cool!
Best, 
Sidney

**Comment by filipbec** [comment]
That's great @chenr2. I really appreciate it.

Just give me a link when you make it public and I will add it to my README.

**Comment by chenr2** [comment]
Thanks @filipbec.  Here's the link:
https://github.com/ribl/FBAnnotationClusteringSwift

Feel free to point out bugs, since there are plenty of times I was translating code I didn't quite understand.
